### ISSUE TITLE
Questions about update, memcache and code example

### ISSUE THREAD

**Issue by supertanuki** [mayeco/GoogleBundle#3]
Hi !

I have 3 questions :
- An update is scheduled for the v201502 of the Google Adwords API?
- Why do you use memcache? Is is required?
- Can we have an example of using this bundle in the readme?

**Comment by mayeco** [comment]
This is fixed in the new v3.0.0

* Adwords 6.0.0 using the new v201502
* Memcache is not required (now use Doctrine Cache)
